import pandas as pd
from sklearn.model_selection import train_test_split
from pathlib import Path

def export_train_test(df: pd.DataFrame, test_size: float = 0.2, random_state: int = 42) -> None:
    """Split the processed DataFrame into train and test sets and save as CSV files.

    Args:
        df: The full processed DataFrame.
        test_size: Proportion of the dataset to include in the test split.
        random_state: Seed for reproducibility.
    """
    train_df, test_df = train_test_split(df, test_size=test_size, random_state=random_state)
    out_dir = Path('data/processed')
    out_dir.mkdir(parents=True, exist_ok=True)
    train_path = out_dir / 'train_processed.csv'
    test_path = out_dir / 'test_processed.csv'
    train_df.to_csv(train_path, index=False)
    test_df.to_csv(test_path, index=False)
    print(f"✅ Exported train_processed.csv ({train_df.shape[0]} rows) and test_processed.csv ({test_df.shape[0]} rows) to {out_dir}")

if __name__ == "__main__":
    # Load the master processed dataset generated by the ETL notebook
    master_path = Path('Students_Addiction_Processed.csv')
    if not master_path.is_file():
        raise FileNotFoundError(f"Processed dataset not found at {master_path}. Run adiccion_etl.ipynb first.")
    df_full = pd.read_csv(master_path)
    export_train_test(df_full)
